### ISSUE TITLE
Strange "Free" value by getting balance

### ISSUE THREAD

**Issue by x777** [nervosnetwork/mercury#299]
Can anybody explain to me, why such things happen? 

Address: ckt1qyq8fh2x2vjtz6hapzgpgwqm8nmu37tm845szcjh7j 
(FULL format: ckt1qjda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsaxagefjfvt2l5yfq9pcrv700j8e0v7kjcl97c7) 

First screenshot before I made faucet for 10000 CKB:
![image](https://user-images.githubusercontent.com/4421831/141867326-9ee228c9-0917-48d2-967d-81dc6e4bfbb6.png)

Second after I made faucet for 10000 CKB, and some amount added to "occupied" value:
![image](https://user-images.githubusercontent.com/4421831/141867340-b0c97094-69c5-40a2-a8c8-e76b8457693c.png)

If reason in the minimum amount of 61 CKB for cell, so why I could transfer to that amount?
Anyway,  explorer shows right (in my logic) balance:

https://explorer.nervos.org/aggron/address/ckt1qjda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsaxagefjfvt2l5yfq9pcrv700j8e0v7kjcl97c7

Thank you in advance!

**Comment by jordanmack** [comment]
I looked at the output and everything seems in order. If you add up the balances of "free" and "occupied", you get the balance from the explorer, ~10233.99.

Yes, what you are seeing is related to the live cell structure, and the minimum CKByte requirements.

Right now you have three live cells. One is an mNFT that requires 133 CKBytes, and the other two are capacity cells requiring 61 CKBytes each, for a total of 255.

The "free" value is CKBytes which are available to use without consuming cells that would change the cell structure. (9978.99 CKBytes)

The "occupied" value is the CKBytes that are used by the three live cells. (255 CKBytes)

If you take the total CKBytes on the address and subtract that which is required to be "occupied" for the current cell structure to exist, you get the free value. (10233.99 - 255 = 9978.99)

**Comment by x777** [comment]
> I looked at the output and everything seems in order. If you add up the balances of "free" and "occupied", you get the balance from the explorer, ~10233.99.
> 
> Yes, what you are seeing is related to the live cell structure, and the minimum CKByte requirements.
> 
> Right now you have three live cells. One is an mNFT that requires 133 CKBytes, and the other two are capacity cells requiring 61 CKBytes each, for a total of 255.
> 
> The "free" value is CKBytes which are available to use without consuming cells that would change the cell structure. (9978.99 CKBytes)
> 
> The "occupied" value is the CKBytes that are used by the three live cells. (255 CKBytes)
> 
> If you take the total CKBytes on the address and subtract that which is required to be "occupied" for the current cell structure to exist, you get the free value. (10233.99 - 255 = 9978.99)

So, to avoid creating new cells at every transfers, need to leave at least 61 CKB, right? 
Another question, after last transfer balance of account was less than 61 CKB, it's because receiver address already had live cell? Can't understand why sometimes I can transfer about whole amount of balance.

I am asking because I am trying to use Mercury as easier way to manage balance of address, and I thought that "free" value already working balance for transferring.

**Comment by jordanmack** [comment]
> So, to avoid creating new cells at every transfer, need to leave at least 61 CKB, right?

Yes, in a basic cell it's 61. In other types of cells it could be more. The mNFT cell on your address is 133.

> under what conditions "occupied" value change by 61?

I think this might be better explained with an example. Say you have two basic live cells:

Cell A: 61 CKB
Cell B: 71 CKB

These are both basic cells, so 61 CKB is the minimum. How much is possible to send? (Ignore tx fees to make this easier.) Since Cell B is > 61, so it can still send 10 CKB. Then you would have this after sending 10 CKB:

Cell A: 61 CKB
Cell B: 61 CKB

You cannot send anymore without changing the cell structure. However, since these are both basic cells they could be combined:

Cell A: 122 CKB

Once combined, you have a single cell that is > 61 CKB. For this reason, you can still send more CKB. What is the amount you can send? The answer is 1-61 CKB, or 122 CKB. You can send a small amount (1-61) so that what is left over is at least 61 CKB, or you can send everything so you have nothing left and the cell is destroyed.

Different cells may have a different minimum other than 61 CKB depending on their type because they take up more space. Remember, 1 CKByte = 1 byte of storage space. The mNFT on your account needs 133 CKB.

I'm not sure if Mercury is able to merge cells like in the example I gave. That would change the "occupied" and "free" values you're talking about. I need to test that.

**Comment by rev-chaos** [comment]
This problem has been fixed in the stable version of v0.2.0 now. Now free CKB is affordable CKB.  @x777 @jordanmack

**Comment by x777** [comment]
> This problem has been fixed in the stable version of v0.2.0 now. Now free CKB is affordable CKB. @x777 @jordanmack

ckb-sdk-go already integrated this stable version?

**Comment by rev-chaos** [comment]
> 

Yes, the latest version v0.101.1
